apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: user-service
type: Opaque
stringData:
  mysql-root-password: root-password
  mysql-user: user_service_user
  mysql-password: user_service_password

