package com.user.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import io.swagger.v3.oas.annotations.media.Schema;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Data Transfer Object for Order entity")
public class OrderDto {
    @Schema(description = "Order ID (auto-generated by MongoDB, null on create)", example = "507f1f77bcf86cd799439011")
    private String id;

    @Schema(description = "Optimistic lock version (for concurrent update detection)", example = "0")
    private Long version;

    @NotBlank(message = "Product name is required")
    @Size(max = 255, message = "Product name must be at most 255 characters")
    @Schema(description = "Name of the product", example = "Laptop", maxLength = 255)
    private String productName;

    @NotNull(message = "Price is required")
    @Positive(message = "Price must be positive")
    @Schema(description = "Price of the order (must be positive)", example = "1299.99")
    private Double price;
}

