version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - sender
      - recipient

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - sender
      - recipient

  micro-sender:
    build: ./micro-sender
    ports:
      - "2026:2026"
    networks:
      - sender

  micro-recipient:
    build: ./micro-recipient
    ports:
      - "2025:2025"
    networks:
      - recipient

  micro-collector:
    build: ./micro-collector
    ports:
      - "2024:2024"
    networks:
      - recipient

networks:
  sender:
    driver: bridge
  recipient:
    driver: bridge
