-- Spring Batch Metadata Tables Schema for MySQL 8.0+

-- CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
--     JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
--     VERSION BIGINT,
--     JOB_NAME VARCHAR(100) NOT NULL,
--     JOB_KEY VARCHAR(32) NOT NULL,
--     UNIQUE KEY (JOB_NAME, JOB_KEY)
-- ) ENGINE=InnoDB;

-- CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
--     JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
--     VERSION BIGINT,
--     JOB_INSTANCE_ID BIGINT NOT NULL,
--     CREATE_TIME DATETIME(6) NOT NULL,
--     START_TIME DATETIME(6),
--     END_TIME DATETIME(6),
--     STATUS VARCHAR(10),
--     EXIT_CODE VARCHAR(2500),
--     EXIT_MESSAGE VARCHAR(2500),
--     LAST_UPDATED DATETIME(6),
--     FOREIGN KEY (JOB_INSTANCE_ID)
--         REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
-- ) ENGINE=InnoDB;

-- CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
--     STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
--     VERSION BIGINT NOT NULL,
--     STEP_NAME VARCHAR(100) NOT NULL,
--     JOB_EXECUTION_ID BIGINT NOT NULL,
--     CREATE_TIME DATETIME(6) NOT NULL,
--     START_TIME DATETIME(6),
--     END_TIME DATETIME(6),
--     STATUS VARCHAR(10),
--     COMMIT_COUNT BIGINT,
--     READ_COUNT BIGINT,
--     FILTER_COUNT BIGINT,
--     WRITE_COUNT BIGINT,
--     READ_SKIP_COUNT BIGINT,
--     WRITE_SKIP_COUNT BIGINT,
--     PROCESS_SKIP_COUNT BIGINT,
--     ROLLBACK_COUNT BIGINT,
--     EXIT_CODE VARCHAR(2500),
--     EXIT_MESSAGE VARCHAR(2500),
--     LAST_UPDATED DATETIME(6),
--     FOREIGN KEY (JOB_EXECUTION_ID)
--         REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
-- ) ENGINE=InnoDB;

-- CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
--     STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
--     SHORT_CONTEXT VARCHAR(2500) NOT NULL,
--     SERIALIZED_CONTEXT LONGTEXT,
--     FOREIGN KEY (STEP_EXECUTION_ID)
--         REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
-- ) ENGINE=InnoDB;

-- CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT (
--     JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
--     SHORT_CONTEXT VARCHAR(2500) NOT NULL,
--     SERIALIZED_CONTEXT LONGTEXT,
--     FOREIGN KEY (JOB_EXECUTION_ID)
--         REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
-- ) ENGINE=InnoDB;

-- CREATE TABLE IF NOT EXISTS BATCH_JOB_SEQ (
--     ID BIGINT NOT NULL,
--     UNIQUE_KEY CHAR(1) NOT NULL,
--     CONSTRAINT UNIQUE_BATCH_JOB_SEQ UNIQUE (UNIQUE_KEY)
-- ) ENGINE=InnoDB;

-- CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ (
--     ID BIGINT NOT NULL,
--     UNIQUE_KEY CHAR(1) NOT NULL,
--     CONSTRAINT UNIQUE_BATCH_JOB_EXECUTION_SEQ UNIQUE (UNIQUE_KEY)
-- ) ENGINE=InnoDB;

-- CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ (
--     ID BIGINT NOT NULL,
--     UNIQUE_KEY CHAR(1) NOT NULL,
--     CONSTRAINT UNIQUE_BATCH_STEP_EXECUTION_SEQ UNIQUE (UNIQUE_KEY)
-- ) ENGINE=InnoDB;

-- INSERT IGNORE INTO BATCH_JOB_SEQ VALUES (0, '0');
-- INSERT IGNORE INTO BATCH_JOB_EXECUTION_SEQ VALUES (0, '0');
-- INSERT IGNORE INTO BATCH_STEP_EXECUTION_SEQ VALUES (0, '0');

-- Run this manually to create Spring Batch metadata tables
-- Copy and paste the uncommented lines into your MySQL client

CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    UNIQUE KEY (JOB_NAME, JOB_KEY)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME(6) NOT NULL,
    START_TIME DATETIME(6),
    END_TIME DATETIME(6),
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED DATETIME(6),
    FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME(6) NOT NULL,
    START_TIME DATETIME(6),
    END_TIME DATETIME(6),
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED DATETIME(6),
    FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT LONGTEXT,
    FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT LONGTEXT,
    FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BATCH_JOB_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT UNIQUE_BATCH_JOB_SEQ UNIQUE (UNIQUE_KEY)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT UNIQUE_BATCH_JOB_EXECUTION_SEQ UNIQUE (UNIQUE_KEY)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT UNIQUE_BATCH_STEP_EXECUTION_SEQ UNIQUE (UNIQUE_KEY)
) ENGINE=InnoDB;

INSERT IGNORE INTO BATCH_JOB_SEQ VALUES (0, '0');
INSERT IGNORE INTO BATCH_JOB_EXECUTION_SEQ VALUES (0, '0');
INSERT IGNORE INTO BATCH_STEP_EXECUTION_SEQ VALUES (0, '0');

