apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: user-service
data:
  MYSQL_DATABASE: user_service_db
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_CACHE_TYPE: "hazelcast"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_USER: "DEBUG"

