apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: ecommerce
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.99.0
          args: ["--config=/etc/otel/otel-collector.yml"]
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 8888
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel/otel-collector.yml
              subPath: otel-collector.yml
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config
