apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  replicas: 1

  selector:
    matchLabels:
      app: otel-collector

  template:
    metadata:
      labels:
        app: otel-collector

    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:latest

          args:
            - "--config=/etc/otel-collector-config.yaml"

          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 8889

          volumeMounts:
            - name: otel-config-volume
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml

      volumes:
        - name: otel-config-volume
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  selector:
    app: otel-collector

  ports:
    - name: grpc
      port: 4317
      targetPort: 4317

    - name: http
      port: 4318
      targetPort: 4318