apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring

data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      debug: {}

      otlp:
        endpoint: tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp, debug]

        metrics:
          receivers: [otlp]
          exporters: [prometheus]

        logs:
          receivers: [otlp]
          exporters: [debug]