apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring

data:
  tempo.yaml: |
    server:
      http_listen_port: 32000

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      max_block_duration: 5m

    compactor:
      compaction:
        compacted_block_retention: 24h

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces
        wal:
          path: /tmp/tempo/wal