apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
spec:
  replicas: 1

  selector:
    matchLabels:
      app: tempo

  template:
    metadata:
      labels:
        app: tempo

    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest

          ports:
            - containerPort: 32000

          volumeMounts:
            - name: tempo-storage
              mountPath: /tmp/tempo

      volumes:
        - name: tempo-storage
          persistentVolumeClaim:
            claimName: tempo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
spec:
  selector:
    app: tempo

  ports:
    - port: 32000
      targetPort: 32000