apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: ecommerce
data:
  SERVER_PORT: "2028"

  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
  SPRING_JPA_SHOW_SQL: "false"

  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_LOCATIONS: classpath:db/migration
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "false"

  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:8080/realms/microservices-realm/protocol/openid-connect/certs"

  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
  SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS: "false"
  SPRING_KAFKA_CONSUMER_GROUP_ID: product-service-alerts
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: com.product.kafka.event
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_USE_TYPE_HEADERS: "false"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE: com.product.kafka.event.ProductEvent

  SPRING_HAZELCAST_CONFIG: classpath:hazelcast.xml
  SPRING_CACHE_TYPE: hazelcast

  CLOUD_AWS_S3_BUCKET: product-images
  CLOUD_AWS_S3_REGION: us-east-1
  CLOUD_AWS_S3_ENDPOINT: "http://minio:9000"

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus,metrics,info
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://otel-collector:4318/v1/traces"
  MANAGEMENT_METRICS_TAGS_APPLICATION: product-service
