server.port=8761
#debug=true
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF

# ── Actuator / Prometheus ──────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,prometheus,metrics,info
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=serviceregistry
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://localhost:30418/v1/traces
