apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: ecommerce
data:
  KEYCLOAK_ADMIN: admin
  KC_DB: dev-file
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY: edge
