apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: ecommerce
data:
  SERVER_PORT: "2026"

  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
  SPRING_JPA_SHOW_SQL: "false"

  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_LOCATIONS: classpath:db/migration
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  SPRING_FLYWAY_BASELINE_VERSION: "0"

  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:8080/realms/microservices-realm/protocol/openid-connect/certs"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: user-service-client
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE: client_credentials
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: "http://keycloak:8080/realms/microservices-realm/protocol/openid-connect/token"

  KEYCLOAK_ADMIN_SERVER_URL: "http://keycloak:8080"
  KEYCLOAK_ADMIN_REALM: microservices-realm

  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
  SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS: "false"

  SPRING_HAZELCAST_CONFIG: classpath:hazelcast.xml
  SPRING_CACHE_TYPE: hazelcast

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus,metrics,info
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://otel-collector:4318/v1/traces"
  MANAGEMENT_METRICS_TAGS_APPLICATION: user-service
