# S3/MinIO credentials for user-service (if needed); MySQL creds in mysql secret.
# echo -n "minioadmin" | base64  →  bWluaW9hZG1pbg==
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ecommerce
type: Opaque
data:
  access-key: bWluaW9hZG1pbg==    # minioadmin — [CHANGE IN PROD]
  secret-key: bWluaW9hZG1pbg==    # minioadmin — [CHANGE IN PROD]
