apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: ecommerce
data:
  SERVER_PORT: "2030"

  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/payment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
  SPRING_JPA_SHOW_SQL: "false"

  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_LOCATIONS: classpath:db/migration
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "false"

  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:8080/realms/microservices-realm/protocol/openid-connect/certs"

  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
  SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS: "false"
  SPRING_KAFKA_PRODUCER_PROPERTIES_MAX_BLOCK_MS: "3000"
  SPRING_KAFKA_PRODUCER_ACKS: all
  SPRING_KAFKA_PRODUCER_PROPERTIES_ENABLE_IDEMPOTENCE: "true"
  SPRING_KAFKA_PRODUCER_RETRIES: "3"
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest

  # Razorpay — disabled until real credentials are configured in secret.yaml
  PAYMENT_GATEWAY_RAZORPAY_ENABLED: "false"

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus,metrics,info
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://otel-collector:4318/v1/traces"
  MANAGEMENT_METRICS_TAGS_APPLICATION: payment-service
