apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: ecommerce
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: apigateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "2027"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: apigateway
          image: ecommerce/apigateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 2027
          envFrom:
            - configMapRef:
                name: apigateway-config
          env:
            - name: GATEWAY_INTERNAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: internal-secret
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-clients-secret
                  key: apigateway-client-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 2027
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 9
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 2027
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 2027
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
