apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-service

resources:
  # Namespace
  - namespace/namespace.yml

  # Secrets and ConfigMap
  - secrets/db-secrets.yml
  - configmap/app-config.yml

  # Storage
  - pv-pvc/mysql-pvc.yml

  # Services
  - services/mysql-service.yml
  - services/user-service-service.yml

  # Deployments
  - deployments/mysql-deployment.yml
  - deployments/user-service-deployment.yml

labels:
  - includeSelectors:
      matchLabels:
        app: user-service
    pairs:
      environment: local

